sendMessage:
  curl --request POST \
 --url https://api.telegram.org/bot6489928685:AAEeFdhMh13ygQ6AV5oZsDBbFitvWqE5MQc/sendMessage \
 --header 'Content-Type: application/json' \
 --data '{
"chat_id": -1002036213982,
"text": "Hello"
}'